version: '3.9'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: semillero
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_OAUTH_REDIRECT_URI: ${GOOGLE_OAUTH_REDIRECT_URI}
      GOOGLE_SCOPES: ${GOOGLE_SCOPES}
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
      - ./prisma:/app/../prisma
    command: npm run start:dev

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
      NODE_ENV: development
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  db_data:
